export const SET_LOADING = 'SET_LOADING'

export const LOGIN = {
    SET_LOGIN: 'SET_LOGIN',
    SET_LOGOUT: 'SET_LOGOUT',
    SET_REGISTER: 'SET_REGISTER',
    SET_ACCOUNT: 'SET_ACCOUNT'
}

export const ACCOUNT = {
    SET_ACCOUNT: 'SET_ACCOUNT',
    SET_ACCOUNTS: 'SET_ACCOUNTS',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_CLEAR_ERROR_MESSAGE: 'SET_CLEAR_ERROR_MESSAGE',
    SET_COUNT: 'SET_COUNT',
}

export const GROUP = {
    SET_GROUPS: 'SET_GROUPS',
}

export const POST = {
    SET_POSTS: 'SET_POSTS',
}

export const TRADINGPOST = {
    SET_TRADINGPOSTS: 'SET_TRADINGPOSTS',
    SET_COUNT: 'SET_COUNT',
}

export const PRIZE = {
    SET_PRIZES: 'SET_PRIZES',
    SET_PRIZE: 'SET_PRIZE',


}

export const CONTEST = {
    SET_CONTEST: 'SET_CONTEST',
    SET_CONTESTS: 'SET_CONTESTS',
    SET_BRANDS: 'SET_BRANDS',
    SET_TYPES: 'SET_TYPES',
    SET_SUBCRIBERS: 'SET_SUBCRIBERS',
    SET_COUNT: 'SET_COUNT',
    SET_PRIZE_CONTEST: 'SET_PRIZE_CONTEST',
    SET_TOP10_SUBMISSIONS: 'SET_TOP10_SUBMISSIONS',
    SET_SUBMISSIONS: 'SET_SUBMISSIONS',
    SET_POST_OF_CONTEST: 'SET_POST_OF_CONTEST',
    SET_PRIZE_FOR_END: 'SET_PRIZE_FOR_END',
}

export const BILL = {
    SET_BILLS: 'SET_BILLS',
    SET_BILL: 'SET_BILL',
    SET_COUNT: 'SET_COUNT'

}

export const FEEDBACK = {
    SET_FEEDBACKS: 'SET_FEEDBACKS',
    FEEDBACK: 'SET_FEEDBACK',
    SET_COUNT: 'SET_COUNT'

}

export const PROPOSAL = {
    SET_PROPOSAL: 'SET_PROPOSAL',
    SET_PROPOSALS: 'SET_PROPOSALS',
    SET_COUNT: 'SET_COUNT',
}